project:
  type: website

website:
  title: "Quarto MWE"
  description: "A minimal working example of a Quarto website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



